'use strict';

const modal =  document.querySelector('.modal');
const overlay = document.querySelector('.overlay');
const btnCloseModal = document.querySelector('.close-modal');
const btnsShowModal = document.querySelectorAll('.show-modal'); // this will give a Nodelist of all the classes within show-modal class

//adding a function expression to close modal

const closeModal = function () {
    modal.classList.add('hidden');
    overlay.classList.add('hidden');
}

const openModal = function() {
    modal.classList.remove('hidden');
    overlay.classList.remove('hidden');
}

for (let i = 0; i < btnsShowModal.length; i++) {
    btnsShowModal[i].addEventListener('click', openModal);
}

//adding functionality to close the modal when clicked on overlay or button. 
btnCloseModal.addEventListener('click', closeModal);
overlay.addEventListener('click', closeModal);

//adding functionality to close the modal when escape key is pressed(a key down event) 
document.addEventListener('keydown', function(e){ // here e is the event object generated by js when any event occurs
    if (e.key === 'Escape' && !modal.classList.contains('hidden')) {
            closeModal();
    }
});